# Generated by Django 5.2.8 on 2026-09-26 06:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindergartenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Humo Kids International Kindergarten', max_length=150)),
                ('address', models.CharField(default='Tashkent city, Chilanzar district, 5th block', max_length=255)),
                ('latitude', models.FloatField(default=41.311081, help_text='Kindergarten GPS Latitude')),
                ('longitude', models.FloatField(default=69.240562, help_text='Kindergarten GPS Longitude')),
                ('geofence_radius_meters', models.FloatField(default=50.0, help_text='Allowed radius in meters')),
                ('daily_meal_rate', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), help_text='Meal cost deducted per excused absent day', max_digits=12)),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('2500000.00'), help_text='Standard monthly tuition fee', max_digits=12)),
                ('currency_symbol', models.CharField(default='UZS', max_length=15)),
                ('contact_phone', models.CharField(default='+998 71 200 00 00', max_length=25)),
                ('contact_email', models.EmailField(default='info@humokids.uz', max_length=254)),
            ],
            options={
                'verbose_name': 'Kindergarten Settings',
                'verbose_name_plural': 'Kindergarten Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director (Superadmin)'), ('MANAGER', 'Manager (Admin)'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='general', help_text='e.g. general, group_1, direct_1_2', max_length=60)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_category', models.CharField(choices=[('JUNIOR', 'Junior Group (Kichik guruh / 2-3 yosh)'), ('MIDDLE', 'Middle Group (O‘rta guruh / 4-5 yosh)'), ('PREPARATORY', 'Preparatory Group (Tayyorlov / 6-7 yosh)')], default='JUNIOR', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(default=25)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('2500000.00'), max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_groups', to=settings.AUTH_USER_MODEL)),
                ('primary_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Boy (O‘g‘il bola)'), ('F', 'Girl (Qiz bola)')], default='M', max_length=1)),
                ('parent_full_name', models.CharField(max_length=120)),
                ('parent_phone', models.CharField(max_length=25)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_notes', models.TextField(blank=True, help_text='Allergies, chronic conditions, special diets, medications', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='kindergarten.group')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='1 to 12')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('2500000.00'), max_digits=12)),
                ('meal_rate', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), max_digits=12)),
                ('excused_days_count', models.PositiveIntegerField(default=0, help_text='Excused absences from previous month')),
                ('recalculation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='excused_days * meal_rate deducted', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('2500000.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid (To‘lanmagan / Qarzdor)'), ('PARTIAL', 'Partially Paid (Qisman to‘langan)'), ('PAID', 'Fully Paid (To‘langan)')], default='UNPAID', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='kindergarten.child')),
            ],
            options={
                'ordering': ['-year', '-month', 'child__first_name'],
                'unique_together': {('child', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash (Naqd)'), ('CARD', 'Bank Card (Plastik karta)'), ('BANK_TRANSFER', 'Bank Transfer (Pul o‘tkazmasi)'), ('CLICK_PAYME', 'Click / Payme Online')], default='CARD', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='kindergarten.monthlyinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Calculated distance to kindergarten in meters', null=True)),
                ('is_within_geofence', models.BooleanField(default=False)),
                ('face_snapshot', models.ImageField(blank=True, null=True, upload_to='face_attendance/')),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified (Hududda va Tasdiqlangan)'), ('REJECTED_GEOFENCE', 'Rejected (Hududdan tashqarida)'), ('ON_TIME', 'On Time (Vaqtida)'), ('LATE', 'Late (Kechikkan)')], default='VERIFIED', max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present (Keldi)'), ('EXCUSED', 'Excused Absence (Sababli)'), ('UNEXCUSED', 'Unexcused Absence (Sababsiz)')], default='PRESENT', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='kindergarten.child')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'child__first_name'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
