# Generated by Django 5.2.8 on 2026-09-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartensettings',
            name='manager_password',
            field=models.CharField(default='humomanager2026', help_text='Manager login password', max_length=128),
        ),
        migrations.AlterField(
            model_name='kindergartensettings',
            name='address',
            field=models.CharField(default='Toshkent sh., Chilonzor tumani, 5-mavze, 18-uy', max_length=255),
        ),
        migrations.AlterField(
            model_name='kindergartensettings',
            name='geofence_radius_meters',
            field=models.FloatField(default=50.0, help_text='Allowed radius in meters from .env'),
        ),
        migrations.AlterField(
            model_name='kindergartensettings',
            name='latitude',
            field=models.FloatField(default=41.376305, help_text='Kindergarten GPS Latitude from .env'),
        ),
        migrations.AlterField(
            model_name='kindergartensettings',
            name='longitude',
            field=models.FloatField(default=69.311778, help_text='Kindergarten GPS Longitude from .env'),
        ),
    ]
