# Generated by Django 5.2.8 on 2026-09-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_kindergartensettings_manager_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kindergarten.group'),
        ),
    ]
