# Generated by Django 6.1.1 on 2026-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0003_alter_child_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik Maosh'),
        ),
    ]
