# Generated by Django 5.2.8 on 2026-09-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0004_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartensettings',
            name='manager_username',
            field=models.CharField(default='manager', help_text='Shared manager login username', max_length=150),
        ),
    ]
