# Generated by Django 5.2.8 on 2026-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0005_add_manager_username_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergartensettings',
            name='work_end_time',
            field=models.TimeField(default='18:00', help_text='Ish tugash vaqti (masalan: 18:00)'),
        ),
        migrations.AddField(
            model_name='kindergartensettings',
            name='work_start_time',
            field=models.TimeField(default='08:00', help_text='Ish boshlanish vaqti (masalan: 08:00)'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim nomi'),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Berilgan boshlang'ich parol"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Direktor'), ('MANAGER', 'Menejer'), ('TEACHER', 'Tarbiyachi'), ('ASSISTANT', 'Yordamchi tarbiyachi / Enaga'), ('NURSE', 'Hamshira'), ('COOK', 'Oshpaz'), ('SECURITY', 'Qorovul'), ('OTHER', 'Boshqa xodim')], default='TEACHER', max_length=20),
        ),
    ]
